### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by agorota** [orbis-developers/home_assistant_viaris#2]
Hi, 
there is no integration in HACS...
How to install?

Thanks

**Comment by HGC72** [comment]
Hi!,
You can install the integration like this:
1.  Go to HACS/integrations.
2.  On the upper right conner there are three points, clik on them and you will see some options. Please, select "Custom repositories".
3.  After that, introduce the repository name https://github.com/orbis-developers/home_assistant_viaris and select "integration" category. You will see "viaris" as a new repository. Click on it and download.
4. It´s important to have the MQTT integration installed.

Regards,

**Comment by agorota** [comment]
Thank you @HGC72 I've connect my-wall box to Home-Assistant!

Congratulations for your excellent work!
