### ISSUE TITLE
Could be posible to change the limited current or power using MQTT?

### ISSUE THREAD

**Issue by Rollerf** [orbis-developers/home_assistant_viaris#7]
Hello @HGC72,

I need to change the power or current limit of the charger in the base of my house consumption. I know that the charger can do this on its own if my house power cable passes through it, but it is not easy in my case. So I would like to know if there is some MQTT topic where I could send a current or power limit. In the event that it is not possible, Could I archive this behavior using the OCPP 1.6J standard?

Thanks for all, best regards.

**Comment by HGC72** [comment]
Hello,
In MQTT, there are no dedicated user topics. However, with OCPP, the availability of this functionality depends on the supported feature profiles of your charger.
Regards,

**Comment by Rollerf** [comment]
Hello,
Thanks for the reply, my doubts are solved.
Regards

**Comment by HGC72** [comment]
Hi,
You´re welcome. I close this issue.
Regards.
