### ISSUE TITLE
Errore file di log

### ISSUE THREAD

**Issue by luca320** [orbis-developers/home_assistant_viaris#8]
Nonostante non abbia mai avuto alcun problema nell'uso dell'integrazione vorrei capire cosa significhi e come possa risolvere l'errore che che trovo regolarmente a distanza di due secondi nel log viewer:

IndexError: list index out of range
2024-06-17 10:26:47.802 ERROR (MainThread) [homeassistant.components.mqtt.client] Exception in mssg_received_rt when handling msg on 'XEO/VIARIS/042F88/stat/0/EVVC37E142F88/streamrt/modulator': '{
	"header":	{
		"timestamp":	1718612807,
		"heapFree":	3795385
	},
	"data":	{
		"uid":	22,
		"maxPower":	6000,
		"limitPower":	6000,
		"limitPowerByPhase":	[6000, 6000, 6000],
		"totalPower":	0,
		"totalPowerByPhase":	[0, 0, 0],
		"battEnergy":	0,
		"battPercent":	0,
		"midLEnabled":	false,
		"midREnabled":	false,
		"totalEnergy":	137202,
		"totalEnergyByPhase":	[137202, 0, 0],
		"homeEnergy":	17098.51,
		"homeEnergyByPhase":	[17098.51, 0, 0],
		"homePower":	0,
		"evsePower":	0,
		"totalCurrent":	[0, 0, 0],
		"splMode":	1,
		"splSlaveFailPower":	6,
		"status":	0,
		"splEvsePower":	0,
		"splEvsePowerByPhase":	[0, 0, 0],
		"splMeter":	3,
		"splMeterAux":	255,
		"relOverload":	0,
		"relOverloadByPhase":	[0, 0, 0],
		"mbusDetected":	false,
		"splDetected":	true,
		"ctxDetected":	true,
		"elements":	[{
				"connectorId":	1,
				"connectorType":	1,
				"connectorName":	"mennekes",
				"state":	1,
				"now":	{
					"timestamp":	1718612803,
					"active":	137202,
					"reactive":	12603,
					"assignment":	0,
					"current":	[0, 0, 0],
					"pfactor":	[0.5, 0, 0],
					"aPow":	[0, 0, 0],
					"rPow":	[0, 0, 0]
				}
			}],
		"splElements":	[{
				"mac":	"7e:14:2f:88",
				"disconnected":	false,
				"isMaster":	true,
				"index":	0,
				"connectorId":	0,
				"flags":	0,
				"pwm":	[0, 0, 0],
				"current":	[0, 0, 0],
				"power":	[0, 0, 0],
				"phase":	[true, false, false],
				"phaseCount":	1,
				"chargeEnergy":	0,
				"totalEnergy":	137202
			}]
	}
}'
Traceback (most recent call last):
  File "/config/custom_components/viaris/number.py", line 203, in mssg_received_rt
    type_connector = data["data"]["elements"][1]["connectorName"]
                     ~~~~~~~~~~~~~~~~~~~~~~~~^^^

**Comment by luca320** [comment]
[errore log.txt](https://github.com/user-attachments/files/15865597/errore.log.txt)

**Comment by HGC72** [comment]
Ciao luca320,

Abbiamo rilasciato una correzione per il problema segnalato con elements[1]["connectorName"] nei messaggi MQTT. Questa aggiornamento è principalmente destinato agli utenti con apparecchiature dotate di un singolo connettore.

Ti invitiamo a aggiornare a questa versione (v0.1.7) per risolvere il problema del registro. 

Grazie per la tua collaborazione e supporto!

Cordiali saluti,

**Comment by luca320** [comment]
Ciao e grazie per la risposta! HA non me lo propone ancora questo aggiornamento, aspetterò! Grazie!Inviato da iPhoneIl giorno 18 giu 2024, alle ore 14:52, HGC72 ***@***.***> ha scritto:﻿
Ciao luca320,
Abbiamo rilasciato una correzione per il problema segnalato con elements[1]["connectorName"] nei messaggi MQTT. Questa aggiornamento è principalmente destinato agli utenti con apparecchiature dotate di un singolo connettore.
Ti invitiamo a aggiornare a questa versione (v0.1.7) per risolvere il problema del registro.
Grazie per la tua collaborazione e supporto!
Cordiali saluti,
